### ISSUE TITLE
$startDate = $calendar->getStart();  and $endDate = $calendar->getEnd(); returns same datetime

### ISSUE THREAD

**Issue by bogdandovgopol** [toiba/FullCalendarBundle#3]
Hi,

Why 
```
$startDate = $calendar->getStart();
$endDate = $calendar->getEnd();
```

return the same datetime?  => it returns `DateTime('now')`

**Comment by tattali** [comment]
Hi can you share more about your listener

**Comment by bogdandovgopol** [comment]
Thanks for the reply,
I actually used listener showed in docs.

```
<?php

namespace App\EventListener;

use App\Repository\ReservationRepository;
use Symfony\Component\Routing\Generator\UrlGeneratorInterface;
use Toiba\FullCalendarBundle\Entity\Event;
use Toiba\FullCalendarBundle\Event\CalendarEvent;

class FullCalendarListener
{

    private $reservationRepository;
    private $router;

    public function __construct(ReservationRepository $reservationRepository, UrlGeneratorInterface $router)
    {
        $this->reservationRepository = $reservationRepository;
        $this->router = $router;
    }

    public function loadEvents(CalendarEvent $calendar): void
    {
        $startDate = $calendar->getStart();
        $endDate = $calendar->getEnd();
        $filters = $calendar->getFilters();

        // Modify the query to fit to your entity and needs
        // Change b.beginAt by your start date in your custom entity
        $bookings = $this->reservationRepository->findAll();

        foreach ($bookings as $booking) {

            // this create the events with your own entity (here booking entity) to populate calendar
            $bookingEvent = new Event(
                $booking->getService()->getName(),
                $booking->getBeginAt(),
                $booking->getEndAt() // If the end date is null or not defined, it creates a all day event
            );

            /*
             * Optional calendar event settings
             *
             * For more information see : Toiba\FullCalendarBundle\Entity\Event
             * and : https://fullcalendar.io/docs/event-object
             */
            // $bookingEvent->setUrl('http://www.google.com');
            // $bookingEvent->setBackgroundColor($booking->getColor());
            // $bookingEvent->setCustomField('borderColor', $booking->getColor());

            if($booking->isAccepted()){
                $bookingEvent->setBackgroundColor('#008000');
            }
            if($booking->isDeclined()){
                $bookingEvent->setBackgroundColor('#FF0000');
            }

            $bookingEvent->setUrl(
                $this->router->generate('reservation_show', [
                    'id' => $booking->getId(),
                ])
            );

            // finally, add the booking to the CalendarEvent for displaying on the calendar
            $calendar->addEvent($bookingEvent);
        }
    }
}
```

Had to use findAll() because calendar was returning the same exact datetimes.

**Comment by tattali** [comment]
did the getBeginAt() and getEndAt() are in your reservation entity ?
else can you show the entity and js

**Comment by tattali** [comment]
where did you put the var dump ?

**Comment by bogdandovgopol** [comment]
dumps were before 
`$this->reservationRepository->findAll();`

Here is my entity:

`<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ReservationRepository")
 */
class Reservation
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="datetime")
     */
    private $beginAt;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $endAt;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $accepted;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $declined;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Service", inversedBy="reservations")
     */
    private $service;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Customer", inversedBy="reservations", cascade={"persist"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $customer;


    private $preferredDate;
    private $availableTimes;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getBeginAt(): ?\DateTimeInterface
    {
        return $this->beginAt;
    }

    public function setBeginAt(\DateTimeInterface $beginAt): self
    {
        $this->beginAt = $beginAt;

        return $this;
    }

    public function getEndAt(): ?\DateTimeInterface
    {
        return $this->endAt;
    }

    public function setEndAt(?\DateTimeInterface $endAt): self
    {
        $this->endAt = $endAt;

        return $this;
    }

    public function isAccepted(): ?bool
    {
        return $this->accepted;
    }

    public function setAccepted(bool $accepted): self
    {
        $this->accepted = $accepted;

        return $this;
    }

    public function isDeclined(): ?bool
    {
        return $this->declined;
    }

    public function setDeclined(bool $declined): self
    {
        $this->declined = $declined;

        return $this;
    }

    public function getService(): ?Service
    {
        return $this->service;
    }

    public function setService(?Service $service): self
    {
        $this->service = $service;

        return $this;
    }

    public function getCustomer(): ?Customer
    {
        return $this->customer;
    }

    public function setCustomer(?Customer $customer): self
    {
        $this->customer = $customer;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getPreferredDate()
    {
        return $this->preferredDate;
    }

    /**
     * @param mixed $preferredDate
     */
    public function setPreferredDate($preferredDate): void
    {
        $this->preferredDate = $preferredDate;
    }

    /**
     * @return mixed
     */
    public function getAvailableTimes()
    {
        return $this->availableTimes;
    }

    /**
     * @param mixed $availableTimes
     */
    public function setAvailableTimes($availableTimes): void
    {
        $this->availableTimes = $availableTimes;
    }





}
`

And JS:

`    <script type="text/javascript">
        $(function () {

            $('#calendar-holder').fullCalendar({
                locale: 'en',
                themeSystem: 'bootstrap4',
                header: {
                    left: 'prev, next, today',
                    center: 'title',
                    right: 'month, agendaWeek, agendaDay'
                },
                defaultView: 'agendaWeek',
                lazyFetching: true,
                navLinks: true,
                selectable: true,
                editable: true,
                eventDurationEditable: true,
                eventSources: [
                    {
                        url: "{{ path('fullcalendar_load_events') }}",
                        type: 'POST',
                        data: {
                            filters: {}
                        },
                        error: function () {
                            // alert('There was an error while fetching FullCalendar!');
                        }
                    }
                ]
            });
        });
    </script>`

**Comment by tattali** [comment]
When I run your code it works to me.
Do you have any `500` error in the network console of your browser?
https://github.com/toiba/FullCalendarBundle/blob/master/doc/doctrine-crud.md#next-steps

**Comment by kironet** [comment]
Please try the example code:

```
$bookings = $this->bookingRepository
            ->createQueryBuilder('b')
            ->andWhere('b.beginAt BETWEEN :startDate and :endDate')
            ->setParameter('startDate', $startDate->format('Y-m-d H:i:s'))
            ->setParameter('endDate', $endDate->format('Y-m-d H:i:s'))
            ->getQuery()
            ->getResult()
        ;
```

This one didn't work for me because `$startDate` and `$endDate` returns the same value `DateTime('now');`

**Comment by bogdandovgopol** [comment]
Please try the example code:

```
$bookings = $this->bookingRepository
            ->createQueryBuilder('b')
            ->andWhere('b.beginAt BETWEEN :startDate and :endDate')
            ->setParameter('startDate', $startDate->format('Y-m-d H:i:s'))
            ->setParameter('endDate', $endDate->format('Y-m-d H:i:s'))
            ->getQuery()
            ->getResult()
        ;
```

This one didn't work for me because `$startDate` and `$endDate` returns the same value `DateTime('now');`

**Comment by tattali** [comment]
you should maybe replace `bookingRepository` by `reservationRepository`

**Comment by tattali** [comment]
with your code I just removes the foreign keys
![Screenshot 2019-03-17 at 19 17 04](https://user-images.githubusercontent.com/10502887/54495937-501a6e00-48e9-11e9-8448-b8fe9cc451af.png)

**Comment by tattali** [comment]
Hi do you find the error ?

**Comment by bogdandovgopol** [comment]
Hi,

Sorry for the late response.
Couldn't find any errors in my code so I  tried to reinstall the whole bundle and now it works...

Thanks for your time and keep a great work!
